name: Generate PDF

on:
  push:
    branches:
    - '*'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex wget alien inkscape \
                                  texlive-lang-chinese fonts-noto-cjk

      - name: Install fonts
        run: |
          sudo cp -r assets/courier/ /usr/share/fonts/courier/

      - name: Make all
        run: make ALL

      - name: upload 4:3
        uses: actions/upload-artifact@v2
        with:
          name: 4-3
          path: /tmp/43/*.pdf

      - name: upload 16:9
        uses: actions/upload-artifact@v2
        with:
          name: 16-9
          path: /tmp/169/*.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' && github.event_name == 'push') }}

    steps:
      - uses: actions/checkout@v2

      - name: Download 4:3
        uses: actions/download-artifact@v2
        with:
          name: 4-3
          path: 43/

      - name: Download 16:9
        uses: actions/download-artifact@v2
        with:
          name: 16-9
          path: 169/

      - name: Zip
        run: |
          zip -r 4-3.zip 43/
          zip -r 16-9.zip 169/

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          custom_tag: auto-release-${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: auto-release-${{ github.sha }}
          release_name: Auto Release ${{ github.sha }}
          body: |
            Automatically created by GitHub Actions
          draft: false
          prerelease: false

      - name: Release 4:3
        id: upload-release-asset-4-3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./4-3.zip
          asset_name: 4-3.zip
          asset_content_type: application/zip

      - name: Release 16:9
        id: upload-release-asset-16-9
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./16-9.zip
          asset_name: 16-9.zip
          asset_content_type: application/zip

