name: Generate PDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex wget alien

      - name: Install fonts
        run: |
          wget https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/32/Everything/aarch64/os/Packages/a/adobe-source-han-sans-cn-fonts-2.001-3.fc32.noarch.rpm
          sudo alien -i adobe-source-han-sans-cn-fonts-2.001-3.fc32.noarch.rpm
          sudo cp -r assets/courier/ /usr/share/fonts/courier/

      - name: Make all
        run: make ALL

