name: Generate PDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex fonts-noto-cjk

      - name: Make all
        run: make ALL
